package report

import (
	"fmt"
	"html/template"
	"os"
	"time"

	"github.com/gjunqueira-sys/ScheduleGate/internal/dcma"
	"github.com/gjunqueira-sys/ScheduleGate/internal/ui"
	"github.com/gjunqueira-sys/ScheduleGate/internal/version"
)

// formatThresholdLabel returns a human-readable threshold string such as "≤ 10%"
// or "≥ 95%", mirroring formatThreshold in excel.go so both reports agree.
func formatThresholdLabel(res dcma.MetricResult) string {
	if res.Threshold == 0.0 {
		return "= 0%"
	}
	if res.Passing && res.Value >= res.Threshold {
		return fmt.Sprintf("≥ %.0f%%", res.Threshold*100)
	}
	if res.Threshold >= 0.90 {
		return fmt.Sprintf("≥ %.0f%%", res.Threshold*100)
	}
	return fmt.Sprintf("≤ %.0f%%", res.Threshold*100)
}

// ReportData holds data for the HTML template.
type ReportData struct {
	ScheduleName  string
	CustomerName  string
	ProjectNumber string
	StatusDate    string
	GeneratedAt   string
	ToolVersion   string
	OverallScore  float64
	PassedCount   int
	TotalCount    int
	Logo          string
	Results       []dcma.MetricResult
}

const htmlTemplate = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Assessment - {{.ScheduleName}}</title>
    <style>
		` + cssStyles + `
    </style>
</head>
<body>
    <div class="container">
        <header>
            <div>
				<pre class="ascii-logo">{{.Logo}}</pre>
                <h1>DCMA Assessment</h1>
            </div>
            <div class="meta-info">
                <div class="meta-item"><span class="meta-label">File:</span> {{.ScheduleName}}</div>
                {{if .CustomerName}}<div class="meta-item"><span class="meta-label">Customer:</span> {{.CustomerName}}</div>{{end}}
                {{if .ProjectNumber}}<div class="meta-item"><span class="meta-label">Project:</span> {{.ProjectNumber}}</div>{{end}}
                {{if .StatusDate}}<div class="meta-item"><span class="meta-label">Status Date:</span> {{.StatusDate}}</div>{{end}}
                <div class="meta-item"><span class="meta-label">Tool:</span> {{.ToolVersion}}</div>
                <div class="meta-item">{{.GeneratedAt}}</div>
            </div>
        </header>

        <div class="card score-container">
            <div class="score-value {{if ge .OverallScore 0.80}}text-success{{else}}text-danger{{end}}">
                {{printf "%.0f" (mul .OverallScore 100)}}%
            </div>
            <div class="score-subtitle">
                Compliance Score • {{.PassedCount}}/{{.TotalCount}} Metrics Passed
            </div>
        </div>

        <div class="card">
			<div class="section-title">Metric Results</div>
            <div class="metrics-list">
                {{range .Results}}
                <div class="metric-row">
					<div style="flex: 1;">
						<div style="display: flex; align-items: center; gap: 1rem; margin-bottom: 0.25rem;">
							{{if .NotApplicable}}
							<span class="badge" style="background:#6c757d;">N/A</span>
							{{else}}
							<span class="badge {{if .Passing}}badge-pass{{else}}badge-fail{{end}}">
								{{if .Passing}}Pass{{else}}Fail{{end}}
							</span>
							{{end}}
							<strong style="font-size: 1.1rem;">{{.Name}}</strong>
						</div>
						<div style="color: var(--text-muted); font-size: 0.85rem;">{{.Description}}</div>
					</div>
					
					<div style="text-align: right; min-width: 150px;">
						{{if .NotApplicable}}
						<div class="cell-num" style="font-size: 1.25rem; color: var(--text-muted);">N/A</div>
						<div style="font-size: 0.8rem; color: var(--text-muted);">Not in export</div>
						{{else}}
						<div class="cell-num {{if .Passing}}text-success{{else}}text-danger{{end}}" style="font-size: 1.25rem;">
							{{printf "%.2f" (mul .Value 100)}}%
						</div>
						<div style="font-size: 0.8rem; color: var(--text-muted);">
							Threshold: {{formatThreshold .MetricResult}}
						</div>
						{{end}}
					</div>
                </div>
				{{end}}
            </div>
        </div>
		
		<footer style="text-align: center; color: var(--border-color); font-size: 0.8rem; margin-top: 3rem;">
			Generated by {{.ToolVersion}}
		</footer>
    </div>
</body>
</html>
`

// GenerateHTML creates an HTML report file.
func GenerateHTML(assessment *dcma.DCMAAssessment, scheduleName, customerName, projectNumber, statusDate, outputPath string) error {
	results := make([]dcma.MetricResult, 0)
	passed := 0

	// Ensure consistent ordering — exclude N/A from pass/total tallying
	metrics := assessment.Metrics
	for _, m := range metrics {
		res := assessment.Results[m.Name()]
		if res.Name != "" && !res.NotApplicable {
			results = append(results, res)
			if res.Passing {
				passed++
			}
		}
	}

	// Creating a view model for the template to allow Description injection
	type MetricViewModel struct {
		dcma.MetricResult
		Description string
	}

	viewResults := make([]MetricViewModel, 0)
	for _, m := range metrics {
		res := assessment.Results[m.Name()]
		viewResults = append(viewResults, MetricViewModel{
			MetricResult: res,
			Description:  m.Description(),
		})
	}

	// Count total applicable metrics (exclude N/A)
	totalApplicable := 0
	for _, m := range metrics {
		res := assessment.Results[m.Name()]
		if !res.NotApplicable {
			totalApplicable++
		}
	}

	data := ReportData{
		ScheduleName:  scheduleName,
		CustomerName:  customerName,
		ProjectNumber: projectNumber,
		StatusDate:    statusDate,
		GeneratedAt:   time.Now().Format("2006-01-02 15:04:05"),
		ToolVersion:   version.Display(),
		OverallScore:  float64(passed) / float64(totalApplicable),
		PassedCount:   passed,
		TotalCount:    totalApplicable,
		Logo:          ui.LogoRaw,
	}

	tmpl, err := template.New("report").Funcs(template.FuncMap{
		"mul":             func(a float64, b int) float64 { return a * float64(b) },
		"formatThreshold": formatThresholdLabel,
	}).Parse(htmlTemplate)

	if err != nil {
		return err
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer f.Close()

	// Pass struct with correct type
	return tmpl.Execute(f, struct {
		ScheduleName  string
		CustomerName  string
		ProjectNumber string
		StatusDate    string
		GeneratedAt   string
		ToolVersion   string
		OverallScore  float64
		PassedCount   int
		TotalCount    int
		Results       []MetricViewModel
		Logo          string
	}{
		ScheduleName:  data.ScheduleName,
		CustomerName:  data.CustomerName,
		ProjectNumber: data.ProjectNumber,
		StatusDate:    data.StatusDate,
		GeneratedAt:   data.GeneratedAt,
		ToolVersion:   data.ToolVersion,
		OverallScore:  data.OverallScore,
		PassedCount:   data.PassedCount,
		TotalCount:    data.TotalCount,
		Results:       viewResults,
		Logo:          data.Logo,
	})
}
