package report

import (
	"encoding/csv"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/gjunqueira-sys/ScheduleGate/internal/compare"
	"github.com/gjunqueira-sys/ScheduleGate/internal/dcma"
	"github.com/gjunqueira-sys/ScheduleGate/internal/model"
	"github.com/gjunqueira-sys/ScheduleGate/internal/reader"
	"github.com/gjunqueira-sys/ScheduleGate/internal/version"
	"github.com/xuri/excelize/v2"
)

func TestGenerateHTML_WritesCompleteReport(t *testing.T) {
	assessment := dcma.NewDCMAAssessment([]int{1, 4, 10})
	assessment.Results = map[string]dcma.MetricResult{
		"Logic": {
			Name: "Logic", Value: 0.02, Threshold: 0.05, Passing: true,
		},
		"Relationship Types": {
			Name: "Relationship Types", Value: 0.95, Threshold: 0.90, Passing: true,
		},
		"Resources": {
			Name: "Resources", Value: 0, Threshold: 0.95, Passing: true, NotApplicable: true,
		},
	}

	out := filepath.Join(t.TempDir(), "assess_report.html")
	err := GenerateHTML(assessment, "sample.csv", "Acme", "P-100", "2026-01-15", out)
	if err != nil {
		t.Fatalf("GenerateHTML returned error: %v", err)
	}

	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated HTML: %v", err)
	}
	html := string(raw)

	if !strings.Contains(html, "</html>") {
		t.Fatal("generated HTML is incomplete: missing closing </html>")
	}
	if !strings.Contains(html, "Threshold:") {
		t.Fatal("generated HTML missing threshold labels")
	}
	if !strings.Contains(html, "≤ 5%") && !strings.Contains(html, "≥ 90%") {
		t.Fatalf("generated HTML missing expected threshold text; got snippet:\n%s", html)
	}
	if !strings.Contains(html, "N/A") {
		t.Fatal("generated HTML missing N/A badge for NotApplicable metric")
	}
}

func TestGenerateHTML_IncludesToolVersion(t *testing.T) {
	assessment := dcma.NewDCMAAssessment([]int{1})
	assessment.Results = map[string]dcma.MetricResult{
		"Logic": {Name: "Logic", Value: 0.02, Threshold: 0.05, Passing: true},
	}

	out := filepath.Join(t.TempDir(), "version_test.html")
	err := GenerateHTML(assessment, "test.csv", "", "", "2026-01-15", out)
	if err != nil {
		t.Fatalf("GenerateHTML returned error: %v", err)
	}

	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated HTML: %v", err)
	}
	html := string(raw)

	if !strings.Contains(html, version.Display()) {
		t.Fatalf("HTML report missing tool version %q", version.Display())
	}
	if !strings.Contains(html, "Generated by "+version.Display()) {
		t.Fatal("HTML report footer missing tool version")
	}
}

func TestGenerateHTML_IncludesStatusDate(t *testing.T) {
	assessment := dcma.NewDCMAAssessment([]int{1})
	assessment.Results = map[string]dcma.MetricResult{
		"Logic": {Name: "Logic", Value: 0.02, Threshold: 0.05, Passing: true},
	}

	out := filepath.Join(t.TempDir(), "status_date_test.html")
	statusDate := "2026-03-15"
	err := GenerateHTML(assessment, "test.csv", "", "", statusDate, out)
	if err != nil {
		t.Fatalf("GenerateHTML returned error: %v", err)
	}

	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated HTML: %v", err)
	}
	html := string(raw)

	if !strings.Contains(html, "Status Date:") {
		t.Fatal("HTML report missing 'Status Date:' label")
	}
	if !strings.Contains(html, statusDate) {
		t.Fatalf("HTML report missing status date %q", statusDate)
	}
}

func TestGenerateHTML_EmptyStatusDateNotShown(t *testing.T) {
	assessment := dcma.NewDCMAAssessment([]int{1})
	assessment.Results = map[string]dcma.MetricResult{
		"Logic": {Name: "Logic", Value: 0.02, Threshold: 0.05, Passing: true},
	}

	out := filepath.Join(t.TempDir(), "empty_status.html")
	err := GenerateHTML(assessment, "test.csv", "", "", "", out)
	if err != nil {
		t.Fatalf("GenerateHTML returned error: %v", err)
	}

	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated HTML: %v", err)
	}
	html := string(raw)

	if strings.Contains(html, "Status Date:") {
		t.Fatal("HTML report should not show 'Status Date:' when empty")
	}
}

func TestGenerateCompareHTML_IncludesToolVersion(t *testing.T) {
	result := &compare.BenchmarkResult{
		OverallScore: 85,
		PillarAScore: 34,
		PillarBScore: 26,
		PillarCScore: 25,
		TotalTasks:   100,
	}

	out := filepath.Join(t.TempDir(), "compare_version.html")
	err := GenerateCompareHTML(result, "prev.xlsx", "curr.xlsx", "2026-01-15", out, false)
	if err != nil {
		t.Fatalf("GenerateCompareHTML returned error: %v", err)
	}

	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated HTML: %v", err)
	}
	html := string(raw)

	if !strings.Contains(html, version.Display()) {
		t.Fatalf("compare HTML report missing tool version %q", version.Display())
	}
	if !strings.Contains(html, "Generated by "+version.Display()) {
		t.Fatal("compare HTML report footer missing tool version")
	}
}

func TestGenerateCompareHTML_IncludesStatusDate(t *testing.T) {
	result := &compare.BenchmarkResult{
		OverallScore: 85,
		PillarAScore: 34,
		PillarBScore: 26,
		PillarCScore: 25,
		TotalTasks:   100,
	}

	out := filepath.Join(t.TempDir(), "compare_status.html")
	statusDate := "2026-06-01"
	err := GenerateCompareHTML(result, "prev.xlsx", "curr.xlsx", statusDate, out, false)
	if err != nil {
		t.Fatalf("GenerateCompareHTML returned error: %v", err)
	}

	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated HTML: %v", err)
	}
	html := string(raw)

	if !strings.Contains(html, "Status Date:") {
		t.Fatal("compare HTML report missing 'Status Date:' label")
	}
	if !strings.Contains(html, statusDate) {
		t.Fatalf("compare HTML report missing status date %q", statusDate)
	}
}

func TestGenerateCompareHTML_EmptyStatusDateNotShown(t *testing.T) {
	result := &compare.BenchmarkResult{
		OverallScore: 85,
		PillarAScore: 34,
		TotalTasks:   100,
	}

	out := filepath.Join(t.TempDir(), "compare_empty_status.html")
	err := GenerateCompareHTML(result, "prev.xlsx", "curr.xlsx", "", out, false)
	if err != nil {
		t.Fatalf("GenerateCompareHTML returned error: %v", err)
	}

	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated HTML: %v", err)
	}
	html := string(raw)

	if strings.Contains(html, "Status Date:") {
		t.Fatal("compare HTML report should not show 'Status Date:' when empty")
	}
}

func TestAppendToCSV_IncludesToolVersion(t *testing.T) {
	assessment := dcma.NewDCMAAssessment([]int{1})
	assessment.Results = map[string]dcma.MetricResult{
		"Logic": {Name: "Logic", Value: 0.02, Threshold: 0.05, Passing: true},
	}

	csvPath := filepath.Join(t.TempDir(), "test.csv")
	err := AppendToCSV(assessment, "test.csv", "Acme", "P-100", "2026-01-15", csvPath)
	if err != nil {
		t.Fatalf("AppendToCSV returned error: %v", err)
	}

	f, err := os.Open(csvPath)
	if err != nil {
		t.Fatalf("opening CSV: %v", err)
	}
	defer f.Close()

	reader := csv.NewReader(f)
	rows, err := reader.ReadAll()
	if err != nil {
		t.Fatalf("reading CSV: %v", err)
	}

	versionCol := -1
	for i, col := range rows[0] {
		if col == "Tool Version" {
			versionCol = i
			break
		}
	}
	if versionCol < 0 {
		t.Fatal("CSV header missing 'Tool Version' column")
	}
	if rows[1][versionCol] != version.Display() {
		t.Fatalf("CSV row Tool Version = %q, want %q", rows[1][versionCol], version.Display())
	}
}

func TestAppendToCSV_IncludesStatusDate(t *testing.T) {
	assessment := dcma.NewDCMAAssessment([]int{1})
	assessment.Results = map[string]dcma.MetricResult{
		"Logic": {Name: "Logic", Value: 0.02, Threshold: 0.05, Passing: true},
	}

	csvPath := filepath.Join(t.TempDir(), "status_test.csv")
	err := AppendToCSV(assessment, "test.csv", "Acme", "P-100", "2026-04-20", csvPath)
	if err != nil {
		t.Fatalf("AppendToCSV returned error: %v", err)
	}

	f, err := os.Open(csvPath)
	if err != nil {
		t.Fatalf("opening CSV: %v", err)
	}
	defer f.Close()

	reader := csv.NewReader(f)
	rows, err := reader.ReadAll()
	if err != nil {
		t.Fatalf("reading CSV: %v", err)
	}

	statusCol := -1
	for i, col := range rows[0] {
		if col == "Status Date" {
			statusCol = i
			break
		}
	}
	if statusCol < 0 {
		t.Fatal("CSV header missing 'Status Date' column")
	}
	if rows[1][statusCol] != "2026-04-20" {
		t.Fatalf("CSV row Status Date = %q, want '2026-04-20'", rows[1][statusCol])
	}
}

func TestAppendToCSV_HeaderColumnsOrder(t *testing.T) {
	assessment := dcma.NewDCMAAssessment([]int{1})
	assessment.Results = map[string]dcma.MetricResult{
		"Logic": {Name: "Logic", Value: 0.02, Threshold: 0.05, Passing: true},
	}

	csvPath := filepath.Join(t.TempDir(), "header_order.csv")
	err := AppendToCSV(assessment, "test.csv", "", "", "2026-01-01", csvPath)
	if err != nil {
		t.Fatalf("AppendToCSV returned error: %v", err)
	}

	f, err := os.Open(csvPath)
	if err != nil {
		t.Fatalf("opening CSV: %v", err)
	}
	defer f.Close()

	reader := csv.NewReader(f)
	rows, err := reader.ReadAll()
	if err != nil {
		t.Fatalf("reading CSV: %v", err)
	}

	expectedOrder := []string{"Customer", "Project", "Schedule Name", "Status Date", "Report Date", "Tool Version", "Overall Score"}
	for i, expected := range expectedOrder {
		if rows[0][i] != expected {
			t.Fatalf("CSV header[%d] = %q, want %q; header=%v", i, rows[0][i], expected, rows[0][:len(expectedOrder)])
		}
	}
}

func TestAppendCompareToCSV_IncludesToolVersion(t *testing.T) {
	result := &compare.BenchmarkResult{
		OverallScore: 85,
		PillarAScore: 34,
		PillarBScore: 26,
		PillarCScore: 25,
		TotalTasks:   100,
	}

	csvPath := filepath.Join(t.TempDir(), "compare_test.csv")
	err := AppendCompareToCSV(result, "prev.xlsx", "curr.xlsx", "Acme", "P-100", "2026-01-15", csvPath)
	if err != nil {
		t.Fatalf("AppendCompareToCSV returned error: %v", err)
	}

	f, err := os.Open(csvPath)
	if err != nil {
		t.Fatalf("opening CSV: %v", err)
	}
	defer f.Close()

	reader := csv.NewReader(f)
	rows, err := reader.ReadAll()
	if err != nil {
		t.Fatalf("reading CSV: %v", err)
	}

	versionCol := -1
	for i, col := range rows[0] {
		if col == "Tool Version" {
			versionCol = i
			break
		}
	}
	if versionCol < 0 {
		t.Fatal("compare CSV header missing 'Tool Version' column")
	}
	if rows[1][versionCol] != version.Display() {
		t.Fatalf("compare CSV row Tool Version = %q, want %q", rows[1][versionCol], version.Display())
	}
}

func TestAppendCompareToCSV_IncludesStatusDate(t *testing.T) {
	result := &compare.BenchmarkResult{
		OverallScore: 85,
		PillarAScore: 34,
		PillarBScore: 26,
		PillarCScore: 25,
		TotalTasks:   100,
	}

	csvPath := filepath.Join(t.TempDir(), "compare_status.csv")
	err := AppendCompareToCSV(result, "prev.xlsx", "curr.xlsx", "Acme", "P-100", "2026-06-15", csvPath)
	if err != nil {
		t.Fatalf("AppendCompareToCSV returned error: %v", err)
	}

	f, err := os.Open(csvPath)
	if err != nil {
		t.Fatalf("opening CSV: %v", err)
	}
	defer f.Close()

	reader := csv.NewReader(f)
	rows, err := reader.ReadAll()
	if err != nil {
		t.Fatalf("reading CSV: %v", err)
	}

	statusCol := -1
	for i, col := range rows[0] {
		if col == "Status Date" {
			statusCol = i
			break
		}
	}
	if statusCol < 0 {
		t.Fatal("compare CSV header missing 'Status Date' column")
	}
	if rows[1][statusCol] != "2026-06-15" {
		t.Fatalf("compare CSV row Status Date = %q, want '2026-06-15'", rows[1][statusCol])
	}
}

func TestGenerateExcelExceptions_IncludesToolVersion(t *testing.T) {
	assessment := dcma.NewDCMAAssessment([]int{1})
	assessment.Results = map[string]dcma.MetricResult{
		"Logic": {Name: "Logic", Value: 0.02, Threshold: 0.05, Passing: true},
	}

	schedule := &model.Schedule{
		Name:     "test.csv",
		DataDate: time.Now(),
	}

	xlsxPath := filepath.Join(t.TempDir(), "version_test.xlsx")
	err := GenerateExcelExceptions(assessment, schedule, "test.csv", "Acme", "P-100", "2026-01-15", xlsxPath)
	if err != nil {
		t.Fatalf("GenerateExcelExceptions returned error: %v", err)
	}

	f, err := excelize.OpenFile(xlsxPath)
	if err != nil {
		t.Fatalf("opening xlsx: %v", err)
	}
	defer f.Close()

	val, err := f.GetCellValue("Summary", "B13")
	if err != nil {
		t.Fatalf("reading cell: %v", err)
	}
	if val != version.Display() {
		t.Fatalf("Excel Tool Version cell = %q, want %q", val, version.Display())
	}
}

func TestGenerateExcelExceptions_IncludesStatusDate(t *testing.T) {
	assessment := dcma.NewDCMAAssessment([]int{1})
	assessment.Results = map[string]dcma.MetricResult{
		"Logic": {Name: "Logic", Value: 0.02, Threshold: 0.05, Passing: true},
	}

	schedule := &model.Schedule{
		Name:     "test.csv",
		DataDate: time.Now(),
	}

	xlsxPath := filepath.Join(t.TempDir(), "status_test.xlsx")
	err := GenerateExcelExceptions(assessment, schedule, "test.csv", "Acme", "P-100", "2026-07-01", xlsxPath)
	if err != nil {
		t.Fatalf("GenerateExcelExceptions returned error: %v", err)
	}

	f, err := excelize.OpenFile(xlsxPath)
	if err != nil {
		t.Fatalf("opening xlsx: %v", err)
	}
	defer f.Close()

	val, err := f.GetCellValue("Summary", "B11")
	if err != nil {
		t.Fatalf("reading cell: %v", err)
	}
	if val != "2026-07-01" {
		t.Fatalf("Excel Status Date cell = %q, want '2026-07-01'", val)
	}
}

// ---------------------------------------------------------------------------
// Anonymous Schedule Integration Tests
// ---------------------------------------------------------------------------

func TestGenerateHTML_AnonymousSchedule(t *testing.T) {
	// Test HTML report generation with the large anonymous test schedule
	r := reader.NewScheduleReader("../../internal/reader/testdata/test_anonymous_schedule.csv")
	sched, err := r.Read()
	if err != nil {
		t.Fatalf("Read() returned error: %v", err)
	}

	// Run assessment
	assessment := dcma.NewDCMAAssessment(nil)
	assessment.Assess(sched)

	// Generate HTML report
	out := filepath.Join(t.TempDir(), "anonymous_report.html")
	statusDate := "2026-04-10"
	err = GenerateHTML(assessment, sched.Name, "Test Customer", "P-TEST", statusDate, out)
	if err != nil {
		t.Fatalf("GenerateHTML returned error: %v", err)
	}

	// Verify HTML file was created and contains expected content
	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated HTML: %v", err)
	}
	html := string(raw)

	if !strings.Contains(html, "</html>") {
		t.Fatal("generated HTML is incomplete: missing closing </html>")
	}
	if !strings.Contains(html, "Test Customer") {
		t.Fatal("generated HTML missing customer name")
	}
	if !strings.Contains(html, statusDate) {
		t.Fatalf("generated HTML missing status date %q", statusDate)
	}
}
