package cmd

import (
	"encoding/csv"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/gjunqueira-sys/ScheduleGate/internal/dcma"
	"github.com/gjunqueira-sys/ScheduleGate/internal/reader"
	"github.com/gjunqueira-sys/ScheduleGate/internal/rules"
	"github.com/gjunqueira-sys/ScheduleGate/internal/version"
)

func TestParseStatusDate(t *testing.T) {
	cases := []struct {
		input   string
		wantErr bool
		wantY   int
		wantM   time.Month
		wantD   int
		desc    string
	}{
		// Accepted formats
		{"2026-04-10", false, 2026, time.April, 10, "YYYY-MM-DD"},
		{"04/10/2026", false, 2026, time.April, 10, "MM/DD/YYYY"},
		{"04-10-2026", false, 2026, time.April, 10, "MM-DD-YYYY"},
		{"04/10/26", false, 2026, time.April, 10, "MM/DD/YY"},
		{"04-10-26", false, 2026, time.April, 10, "MM-DD-YY"},

		// Whitespace trimming
		{"  2026-04-10  ", false, 2026, time.April, 10, "YYYY-MM-DD with surrounding spaces"},

		// Additional valid dates
		{"2025-01-22", false, 2025, time.January, 22, "YYYY-MM-DD January"},
		{"01/22/2025", false, 2025, time.January, 22, "MM/DD/YYYY January"},
		{"12/31/2025", false, 2025, time.December, 31, "MM/DD/YYYY December"},

		// Error cases
		{"April 10", true, 0, 0, 0, "long month name (unsupported)"},
		{"", true, 0, 0, 0, "empty string"},
		{"10/04/2026", false, 2026, time.October, 4, "ambiguous MM/DD — treated as October 4, not April 10"},
		{"not-a-date", true, 0, 0, 0, "garbage input"},
		{"2026/04/10", true, 0, 0, 0, "YYYY/MM/DD slash (unsupported)"},
	}

	for _, tc := range cases {
		t.Run(tc.desc, func(t *testing.T) {
			got, err := parseStatusDate(tc.input, "US")
			if tc.wantErr {
				if err == nil {
					t.Errorf("parseStatusDate(%q) = %v, want error", tc.input, got)
				}
				return
			}
			if err != nil {
				t.Fatalf("parseStatusDate(%q) returned error: %v", tc.input, err)
			}
			if got.Year() != tc.wantY || got.Month() != tc.wantM || got.Day() != tc.wantD {
				t.Errorf("parseStatusDate(%q) = %s, want %04d-%02d-%02d",
					tc.input, got.Format("2006-01-02"), tc.wantY, int(tc.wantM), tc.wantD)
			}
		})
	}
}

func TestParseStatusDate_EULocale(t *testing.T) {
	cases := []struct {
		input string
		wantY int
		wantM time.Month
		wantD int
		desc  string
	}{
		{"22/01/2025", 2025, time.January, 22, "DD/MM/YYYY (EU primary)"},
		{"22-01-2025", 2025, time.January, 22, "DD-MM-YYYY (EU dash)"},
		{"22/01/25", 2025, time.January, 22, "DD/MM/YY (EU short)"},
		{"05/04/2026", 2026, time.April, 5, "ambiguous date → April 5 in EU locale"},
	}

	for _, tc := range cases {
		t.Run(tc.desc, func(t *testing.T) {
			got, err := parseStatusDate(tc.input, "EU")
			if err != nil {
				t.Fatalf("parseStatusDate(%q, EU) returned error: %v", tc.input, err)
			}
			if got.Year() != tc.wantY || got.Month() != tc.wantM || got.Day() != tc.wantD {
				t.Errorf("parseStatusDate(%q, EU) = %s, want %04d-%02d-%02d",
					tc.input, got.Format("2006-01-02"), tc.wantY, int(tc.wantM), tc.wantD)
			}
		})
	}
}

func TestParseStatusDate_ErrorMessage(t *testing.T) {
	_, err := parseStatusDate("bad-date", "US")
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	msg := err.Error()
	if msg == "" {
		t.Error("error message should not be empty")
	}
	// Verify the error message contains the problematic input
	if len(msg) < 5 {
		t.Errorf("error message too short: %q", msg)
	}
}

func TestGenerateValidationHTML_IncludesToolVersion(t *testing.T) {
	result := &reader.ColumnValidationResult{
		Found: map[string]string{
			"task_id":          "ID",
			"task_name":        "Name",
			"duration":         "Duration",
			"start":            "Start",
			"finish":           "Finish",
			"percent_complete": "% Complete",
			"predecessors":     "Predecessors",
		},
		Extra:    []string{"Notes"},
		Warnings: nil,
	}

	out := filepath.Join(t.TempDir(), "validate_version.html")
	reportTS := "2026-01-15 10:30:00"
	err := generateValidationHTML(result, "test.xlsx", out, reportTS)
	if err != nil {
		t.Fatalf("generateValidationHTML returned error: %v", err)
	}

	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated HTML: %v", err)
	}
	html := string(raw)

	if !strings.Contains(html, version.Display()) {
		t.Fatalf("validation HTML missing tool version %q", version.Display())
	}
	if !strings.Contains(html, "Generated by "+version.Display()) {
		t.Fatal("validation HTML footer missing tool version")
	}
}

func TestGenerateValidationHTML_IncludesReportTimestamp(t *testing.T) {
	result := &reader.ColumnValidationResult{
		Found: map[string]string{
			"task_id": "ID",
		},
		Extra:    nil,
		Warnings: nil,
	}

	out := filepath.Join(t.TempDir(), "validate_ts.html")
	reportTS := "2026-06-15 14:45:00"
	err := generateValidationHTML(result, "test.xlsx", out, reportTS)
	if err != nil {
		t.Fatalf("generateValidationHTML returned error: %v", err)
	}

	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated HTML: %v", err)
	}
	html := string(raw)

	if !strings.Contains(html, reportTS) {
		t.Fatalf("validation HTML missing report timestamp %q", reportTS)
	}
}

func TestAppendValidationCSV_IncludesToolVersion(t *testing.T) {
	result := &reader.ColumnValidationResult{
		Found: map[string]string{
			"task_id": "ID",
		},
		Extra:    nil,
		Warnings: nil,
	}

	csvPath := filepath.Join(t.TempDir(), "validate_version.csv")
	err := appendValidationCSV(result, "test.xlsx", csvPath, "2026-01-15 10:00:00")
	if err != nil {
		t.Fatalf("appendValidationCSV returned error: %v", err)
	}

	f, err := os.Open(csvPath)
	if err != nil {
		t.Fatalf("opening CSV: %v", err)
	}
	defer f.Close()

	reader := csv.NewReader(f)
	rows, err := reader.ReadAll()
	if err != nil {
		t.Fatalf("reading CSV: %v", err)
	}

	versionCol := -1
	for i, col := range rows[0] {
		if col == "Tool Version" {
			versionCol = i
			break
		}
	}
	if versionCol < 0 {
		t.Fatal("validation CSV header missing 'Tool Version' column")
	}
	if rows[1][versionCol] != version.Display() {
		t.Fatalf("validation CSV row Tool Version = %q, want %q", rows[1][versionCol], version.Display())
	}
}

func TestAppendValidationCSV_IncludesReportDate(t *testing.T) {
	result := &reader.ColumnValidationResult{
		Found: map[string]string{
			"task_id": "ID",
		},
		Extra:    nil,
		Warnings: nil,
	}

	csvPath := filepath.Join(t.TempDir(), "validate_ts.csv")
	reportTS := "2026-07-01 12:00:00"
	err := appendValidationCSV(result, "test.xlsx", csvPath, reportTS)
	if err != nil {
		t.Fatalf("appendValidationCSV returned error: %v", err)
	}

	f, err := os.Open(csvPath)
	if err != nil {
		t.Fatalf("opening CSV: %v", err)
	}
	defer f.Close()

	reader := csv.NewReader(f)
	rows, err := reader.ReadAll()
	if err != nil {
		t.Fatalf("reading CSV: %v", err)
	}

	dateCol := -1
	for i, col := range rows[0] {
		if col == "Report Date" {
			dateCol = i
			break
		}
	}
	if dateCol < 0 {
		t.Fatal("validation CSV header missing 'Report Date' column")
	}
	if rows[1][dateCol] != reportTS {
		t.Fatalf("validation CSV row Report Date = %q, want %q", rows[1][dateCol], reportTS)
	}
}

func TestGeneratePatternsHTML_IncludesToolVersion(t *testing.T) {
	var results []rules.RuleResult
	out := filepath.Join(t.TempDir(), "patterns_version.html")
	reportTS := "2026-01-15 10:30:00"
	err := generatePatternsHTML(results, "test.xlsx", "rules.yaml", out, false, reportTS)
	if err != nil {
		t.Fatalf("generatePatternsHTML returned error: %v", err)
	}

	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated HTML: %v", err)
	}
	html := string(raw)

	if !strings.Contains(html, version.Display()) {
		t.Fatalf("patterns HTML missing tool version %q", version.Display())
	}
	if !strings.Contains(html, "Generated by "+version.Display()) {
		t.Fatal("patterns HTML footer missing tool version")
	}
}

func TestGeneratePatternsHTML_IncludesReportTimestamp(t *testing.T) {
	var results []rules.RuleResult
	out := filepath.Join(t.TempDir(), "patterns_ts.html")
	reportTS := "2026-08-15 09:00:00"
	err := generatePatternsHTML(results, "test.xlsx", "rules.yaml", out, false, reportTS)
	if err != nil {
		t.Fatalf("generatePatternsHTML returned error: %v", err)
	}

	raw, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated HTML: %v", err)
	}
	html := string(raw)

	if !strings.Contains(html, reportTS) {
		t.Fatalf("patterns HTML missing report timestamp %q", reportTS)
	}
}

func TestAppendPatternsCSV_IncludesToolVersion(t *testing.T) {
	results := []rules.RuleResult{
		{
			Rule:  rules.Rule{Name: "Substation Layout", MinCount: 1},
			Count: 2, Passing: true,
		},
	}

	csvPath := filepath.Join(t.TempDir(), "patterns_version.csv")
	err := appendPatternsCSV(results, "test.xlsx", csvPath, "2026-01-15 10:00:00")
	if err != nil {
		t.Fatalf("appendPatternsCSV returned error: %v", err)
	}

	f, err := os.Open(csvPath)
	if err != nil {
		t.Fatalf("opening CSV: %v", err)
	}
	defer f.Close()

	reader := csv.NewReader(f)
	rows, err := reader.ReadAll()
	if err != nil {
		t.Fatalf("reading CSV: %v", err)
	}

	versionCol := -1
	for i, col := range rows[0] {
		if col == "Tool Version" {
			versionCol = i
			break
		}
	}
	if versionCol < 0 {
		t.Fatal("patterns CSV header missing 'Tool Version' column")
	}
	if rows[1][versionCol] != version.Display() {
		t.Fatalf("patterns CSV row Tool Version = %q, want %q", rows[1][versionCol], version.Display())
	}
}

func TestAppendPatternsCSV_IncludesReportDate(t *testing.T) {
	results := []rules.RuleResult{
		{
			Rule:  rules.Rule{Name: "Substation Layout", MinCount: 1},
			Count: 2, Passing: true,
		},
	}

	csvPath := filepath.Join(t.TempDir(), "patterns_ts.csv")
	reportTS := "2026-09-01 08:00:00"
	err := appendPatternsCSV(results, "test.xlsx", csvPath, reportTS)
	if err != nil {
		t.Fatalf("appendPatternsCSV returned error: %v", err)
	}

	f, err := os.Open(csvPath)
	if err != nil {
		t.Fatalf("opening CSV: %v", err)
	}
	defer f.Close()

	reader := csv.NewReader(f)
	rows, err := reader.ReadAll()
	if err != nil {
		t.Fatalf("reading CSV: %v", err)
	}

	dateCol := -1
	for i, col := range rows[0] {
		if col == "Report Date" {
			dateCol = i
			break
		}
	}
	if dateCol < 0 {
		t.Fatal("patterns CSV header missing 'Report Date' column")
	}
	if rows[1][dateCol] != reportTS {
		t.Fatalf("patterns CSV row Report Date = %q, want %q", rows[1][dateCol], reportTS)
	}
}

// ---------------------------------------------------------------------------
// Anonymous Schedule Integration Tests
// ---------------------------------------------------------------------------

func TestAssess_AnonymousSchedule(t *testing.T) {
	// Test assessment of the large anonymous test schedule
	// This is an integration test that validates the full assessment pipeline
	// works with a realistic, large-scale schedule (6000+ tasks)
	
	r := reader.NewScheduleReader("../internal/reader/testdata/test_anonymous_schedule.csv")
	sched, err := r.Read()
	if err != nil {
		t.Fatalf("Read() returned error: %v", err)
	}

	// Verify schedule loaded correctly
	if len(sched.Tasks) == 0 {
		t.Fatal("expected tasks in schedule")
	}

	// Set status date for consistent testing
	sched.DataDate = time.Date(2026, 4, 10, 0, 0, 0, 0, time.UTC)

	// Run assessment
	assessment := dcma.NewDCMAAssessment(nil)
	assessment.Assess(sched)

	// Verify all 14 metrics were assessed
	if len(assessment.Metrics) != 14 {
		t.Errorf("expected 14 metrics, got %d", len(assessment.Metrics))
	}

	// Verify results exist for all metrics
	for _, m := range assessment.Metrics {
		result, ok := assessment.Results[m.Name()]
		if !ok {
			t.Errorf("missing result for metric %s", m.Name())
		}
		// Verify result has required fields
		if result.Name == "" {
			t.Errorf("metric %s has empty name", m.Name())
		}
		if result.Value < 0 || result.Value > 1 {
			t.Errorf("metric %s value out of range [0,1]: %f", m.Name(), result.Value)
		}
	}
}

func TestAssess_AnonymousSchedule_NoIdentifyingReferences(t *testing.T) {
	// Verify the anonymous schedule has no identifying references
	r := reader.NewScheduleReader("../internal/reader/testdata/test_anonymous_schedule.csv")
	sched, err := r.Read()
	if err != nil {
		t.Fatalf("Read() returned error: %v", err)
	}

	// Check all task names and disciplines for identifying strings
	identifyingStrings := []string{"ross", "demat", "grainger"}
	for _, task := range sched.Tasks {
		nameLower := strings.ToLower(task.Name)
		discLower := strings.ToLower(task.Discipline)
		for _, ident := range identifyingStrings {
			if strings.Contains(nameLower, ident) {
				t.Errorf("task %s name contains identifying string %q: %q", task.TaskID, ident, task.Name)
			}
			if strings.Contains(discLower, ident) {
				t.Errorf("task %s discipline contains identifying string %q: %q", task.TaskID, ident, task.Discipline)
			}
		}
	}
}
